x = "Hello World"
x = 20
x = 20.0
x = True
x = 1j
x = {"name" : "John", "age" : 36}
x = range(0,4)
x = [1,"2",3]
x = (1,"2",3)
x = set(1,"2",3)
x = {1,"2",3}
x = frozenset({"apple", "banana", "cherry"})
x = b"Hello"	
x = bytearray(5)		
x = memoryview(bytes(5))	
x = None
